apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-mtaylor-io
spec:
  template:
    spec:
      containers:
      - name: events
        image: images.home.mtaylor.io/events-mtaylor-io
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: events-mtaylor-io
              key: host
        - name: MTAYLOR_IO_USERNAME
          valueFrom:
            configMapKeyRef:
              name: events-mtaylor-io
              key: username
        - name: MTAYLOR_IO_PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: events-mtaylor-io
              key: public-key
        - name: MTAYLOR_IO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: events-mtaylor-io
              key: secret-key
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: events-mtaylor-io
              key: postgres-host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: events-mtaylor-io
              key: postgres-port
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: events-mtaylor-io
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: events-mtaylor-io
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: events-mtaylor-io
              key: postgres-db
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 3
          initialDelaySeconds: 5
          timeoutSeconds: 1
          tcpSocket:
            port: http
