apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: events-mtaylor-io
commonLabels:
  app: events-mtaylor-io
resources:
- deployment.yml
- service.yml
images:
- name: images.home.mtaylor.io/events-mtaylor-io
  newTag: 0.0.2
